#pragma once
#include "lib/function_pairs.h"

#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"

#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Differential / ablation mode (T2.1)
// ---------------------------------------------------------------------------
// Heuristics named here are evaluated but their verdict is suppressed —
// the pair is NOT filtered even if the heuristic says it would be.
// Used to measure how many additional No verdicts each heuristic is
// currently hiding (potential FNs).  See --disable-heuristic CLI flag.
// Names must match PairHeuristic::name() exactly (case-sensitive).
void setDisabledHeuristics(std::set<std::string> names);
const std::set<std::string> &disabledHeuristics();

// ---------------------------------------------------------------------------
// Cross-TU init/exit seeds (v14 path 1)
// ---------------------------------------------------------------------------
// External feeders (the kernel runner) compute the global init-only and
// exit-only function-name closures across all .ll files (so hidden-linkage
// wrappers whose entire global caller set is init-only get included) and
// pass the result to every mbcheck invocation via these setters.  The names
// are added to the LifecycleHeuristic seed sets *before* the per-module H27
// fixpoint, expanding the suppression coverage to functions whose init-only
// status only becomes visible from outside this TU.
void setExtraInitOnly(std::set<std::string> names);
void setExtraExitOnly(std::set<std::string> names);
const std::set<std::string> &extraInitOnly();
const std::set<std::string> &extraExitOnly();

// ---------------------------------------------------------------------------
// PairHeuristic — abstract interface for mutual-exclusion heuristics.
//
// Subclass and implement isMutuallyExclusive() to indicate that the two
// functions in a FunctionPair run in the same sequential execution context
// (and therefore cannot be concurrently accessing shared state).  Returning
// true causes the pair to be filtered out of the final result.
//
// To register a new heuristic: subclass PairHeuristic, implement the method,
// and append an instance to the vector in FnHeuristicsFilterPass::run().
// ---------------------------------------------------------------------------
class PairHeuristic {
public:
    virtual ~PairHeuristic() = default;

    // Short identifier used in stats output (e.g. "CallGraph", "LockAlias").
    virtual const char *name() const = 0;

    // Returns a non-empty sub-category string if the pair is suppressed by this
    // heuristic, or an empty string if not.  The sub-category is emitted as
    // STATS:heuristic_sub:<name>:<subcat>=<count> for detailed breakdowns.
    virtual std::string isMutuallyExclusive(const FunctionPair      &pair,
                                            llvm::Module             &M,
                                            llvm::ModuleAnalysisManager &MAM) const = 0;
};

// ---------------------------------------------------------------------------
// BenignAnchorHeuristic (H_BA)
//
// Suppresses pairs whose ordering anchor is a known-benign, non-ordering
// call — specifically WARN_ONCE / BUG patterns.  These arise when the
// anchor call writes an idempotent once-write static flag rather than
// performing real inter-thread synchronization.
//
// Covered patterns:
//   __warn_printk  — exclusively generated by WARN_ONCE() / BUG(); always
//                    paired with a .__already_done static flag as the
//                    anchor-alloc object.  Safe to suppress unconditionally.
//   _printk + .__already_done anchorAlloc — WARN_ONCE / pr_warn_once
//                    pattern identified by the anchorAlloc object suffix.
// ---------------------------------------------------------------------------
class BenignAnchorHeuristic : public PairHeuristic {
public:
    const char *name() const override { return "BenignAnchor"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// ReadReadPair (H_RR)
//
// Sound: a data race requires at least one WRITE.  If the anchor bracket's
// shared accesses (before + after) are ALL loads AND every partner-function
// access is a load, the pair cannot constitute a data race — no memory
// location is written concurrently.
//
// This is the cheapest and most impactful heuristic: no PTA, no call graph.
// It must be evaluated SECOND in the heuristic chain (after BenignAnchor).
//
// Anchor-side stores are detected via SharedAccess::Kind (set by
// CausalDetectPass).  Partner-side stores are detected by inspecting the
// PartnerAccess::irInst string: plain LLVM stores begin with "store ";
// inline-asm stores (stlr, swpal) are recognised by substring match.
// ---------------------------------------------------------------------------
class ReadReadPair : public PairHeuristic {
public:
    const char *name() const override { return "ReadRead"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// CallGraphHeuristic
//
// A pair (anchorFn, partnerFn) is mutually exclusive when one function is
// transitively reachable from the other in the module's call graph — i.e.
// one calls the other, directly or through a chain of calls.  Such functions
// always run in the same thread context and cannot be concurrent.
//
// If there are multiple call-graph paths (e.g. multiple callers of a shared
// helper), reachability through ANY single path is sufficient to declare the
// pair mutually exclusive.  Module-entry functions with no in-edges (such as
// init_module / cleanup_module) are unreachable from each other and are
// therefore NOT filtered.
//
// G5.2 IRQ-context correction: if one function is in `irqReachable_` and the
// other is not, call-graph reachability does NOT imply mutex — the irq handler
// (or work/tasklet callback) runs in a different execution context than its
// registering caller, and the two CAN run concurrently on different CPUs.
// ---------------------------------------------------------------------------
class CallGraphHeuristic : public PairHeuristic {
    std::set<std::string> irqReachable_;
public:
    CallGraphHeuristic() = default;
    explicit CallGraphHeuristic(std::set<std::string> irqReachable)
        : irqReachable_(std::move(irqReachable)) {}

    const char *name() const override { return "CallGraph"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                             llvm::Module             &M,
                             llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// LockAliasHeuristic
//
// A pair (anchorFn, partnerFn) is mutually exclusive when both functions
// acquire the same exclusive kernel lock (spin_lock, mutex_lock, etc.) on
// the same lock variable.  If both hold the same lock, only one can be in
// the critical section at any time — they cannot run concurrently.
//
// Lock sets are pre-computed by FnHeuristicsFilterPass::run() using SVF
// pointer analysis: the set of base-object NodeIDs of every lock variable
// each function acquires via an exclusive acquire call.  This class receives
// those sets at construction time and checks for non-empty intersection.
//
// "Exclusive" lock acquires recognised (argument 0 is the lock pointer):
//   _raw_spin_lock*, mutex_lock*, down*, _raw_write_lock*
//
// NOT included (do not imply mutual exclusion between two callers):
//   __rcu_read_lock (no argument, readers run concurrently)
//   _raw_read_lock* (multiple readers may hold simultaneously)
// ---------------------------------------------------------------------------
class LockAliasHeuristic : public PairHeuristic {
    // function name → set of base-object NodeIDs of exclusive locks acquired
    std::map<std::string, std::set<unsigned>> lockSets_;
    // NodeID → global variable name (for sub-category reporting)
    std::map<unsigned, std::string> lockNames_;
public:
    LockAliasHeuristic(
        std::map<std::string, std::set<unsigned>> lockSets,
        std::map<unsigned, std::string> lockNames)
        : lockSets_(std::move(lockSets)), lockNames_(std::move(lockNames)) {}

    const char *name() const override { return "LockAlias"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// LifecycleHeuristic (H5 + H6 + H27)
//
// A pair (anchorFn, partnerFn) is mutually exclusive when one function runs
// exclusively during module initialisation and the other exclusively during
// module teardown.  Init and exit phases never overlap: the kernel ensures
// all prior users have released the module before cleanup_module runs.
//
// "Init-only": transitively reachable only from functions in .init.text
//              (i.e. __init-marked functions) and not reachable from any
//              .exit.text function.
// "Exit-only": symmetric — reachable only from .exit.text functions.
//
// Detection is section-based so it does not depend on naming conventions.
//
// "Module-init-only" (H27): functions transitively reachable EXCLUSIVELY from
// module_init (__initstub__* or .init.text) via internal-linkage calls only.
// Because module_init completes before any exported symbol becomes visible,
// these functions cannot run concurrently with runtime or exit-phase functions.
// Any pair where EITHER function is module-init-only is filtered.
//
// "Module-exit-only" (H27): symmetric — reachable exclusively from .exit.text
// via internal-linkage calls.  module_exit runs after all in-flight calls
// have drained (module reference count reaches zero), so module-exit-only
// functions also cannot be concurrent with runtime or init-phase functions.
// ---------------------------------------------------------------------------
class LifecycleHeuristic : public PairHeuristic {
    std::set<std::string> initOnly_;       // functions reachable only from init
    std::set<std::string> exitOnly_;       // functions reachable only from exit
    std::set<std::string> moduleInitOnly_; // transitively module-init-only (H27)
    std::set<std::string> moduleExitOnly_; // transitively module-exit-only (H27)
public:
    LifecycleHeuristic(std::set<std::string> initOnly,
                       std::set<std::string> exitOnly,
                       std::set<std::string> moduleInitOnly,
                       std::set<std::string> moduleExitOnly)
        : initOnly_(std::move(initOnly)), exitOnly_(std::move(exitOnly)),
          moduleInitOnly_(std::move(moduleInitOnly)),
          moduleExitOnly_(std::move(moduleExitOnly)) {}

    const char *name() const override { return "Lifecycle"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// RcuSerialHeuristic (H3 + H16)
//
// A pair is ordered when one function is inside an RCU read-side critical
// section (calls rcu_read_lock / __rcu_read_lock / __srcu_read_lock) and the
// other calls synchronize_rcu / synchronize_srcu (or the expedited variants).
// These blocking variants guarantee that synchronize_* returns only after all
// prior readers have exited — a strict happens-before relationship.
//
// NOTE: call_rcu / call_srcu are intentionally excluded.  They schedule a
// callback asynchronously and return immediately — the calling function CAN
// overlap with active RCU readers, so they provide no mutual exclusion.
// ---------------------------------------------------------------------------
class RcuSerialHeuristic : public PairHeuristic {
    std::set<std::string> rcuReaders_;   // functions calling rcu_read_lock
    std::set<std::string> rcuSync_;      // functions calling synchronize_rcu/*_srcu
public:
    RcuSerialHeuristic(std::set<std::string> readers,
                       std::set<std::string> sync)
        : rcuReaders_(std::move(readers)), rcuSync_(std::move(sync)) {}

    const char *name() const override { return "RcuSerial"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// SeqlockRetryHeuristic
//
// One side brackets its stores in write_seqlock/write_sequnlock, the other
// reads under read_seqbegin/read_seqretry.  The reader takes no lock and may
// observe a torn value; read_seqretry detects the concurrent write and the
// caller loops, so the pair is not a publication defect.
// ---------------------------------------------------------------------------
class SeqlockRetryHeuristic : public PairHeuristic {
    std::set<std::string> writers_;
    std::set<std::string> readers_;
public:
    SeqlockRetryHeuristic(std::set<std::string> writers,
                          std::set<std::string> readers)
        : writers_(std::move(writers)), readers_(std::move(readers)) {}

    const char *name() const override { return "SeqlockRetry"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// CompletionOrderHeuristic (H14)
//
// A pair is mutually exclusive (strictly ordered) when one function calls
// complete(X) — signalling a kernel completion — and the other calls
// wait_for_completion(X) on the same completion object X.
// wait_for_completion returns only after complete has been called, so the
// two functions execute in a strict producer-before-consumer order.
//
// Object identity is established via SVF pointer analysis: the base-object
// NodeID of the completion pointer argument is used for matching.
// ---------------------------------------------------------------------------
class CompletionOrderHeuristic : public PairHeuristic {
    // function name → set of completion base-object IDs signalled by that fn
    std::map<std::string, std::set<unsigned>> signal_;
    // function name → set of completion base-object IDs waited on by that fn
    std::map<std::string, std::set<unsigned>> wait_;
public:
    CompletionOrderHeuristic(
        std::map<std::string, std::set<unsigned>> signal,
        std::map<std::string, std::set<unsigned>> wait)
        : signal_(std::move(signal)), wait_(std::move(wait)) {}

    const char *name() const override { return "CompletionOrder"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// IrqSerialHeuristic (H20)
//
// H20: One function calls disable_irq(N) / synchronize_irq(N) to drain the
//      IRQ line N, and the other function's name matches the IRQ-handler
//      naming convention (*_irq* / *_isr* / *_interrupt*).  The drain
//      guarantees a strict happens-before ordering.
//
// NOTE: H4 ("both fns call local_bh_disable") is intentionally NOT
// implemented.  local_bh_disable is CPU-local: it only prevents reentrancy
// on the SAME CPU.  Two functions on different CPUs with BH disabled are
// still fully concurrent.  NB patterns (smp_store_release / smp_load_acquire)
// exist precisely for cross-CPU ordering, so H4 can never be a sound filter
// for any pair this tool reports.
// ---------------------------------------------------------------------------
class IrqSerialHeuristic : public PairHeuristic {
    std::set<std::string> irqDisablers_;   // kept but unused after H4 removal
    std::set<std::string> irqSyncCallers_; // fns that call disable_irq/synchronize_irq
public:
    IrqSerialHeuristic(std::set<std::string> disablers,
                       std::set<std::string> syncCallers)
        : irqDisablers_(std::move(disablers)),
          irqSyncCallers_(std::move(syncCallers)) {}

    const char *name() const override { return "IrqSerial"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// SubsystemLockHeuristic (H13)
//
// Both functions call the same zero-argument global subsystem lock —
// rtnl_lock(), netdev_lock(), pci_lock_rescan_remove(), etc.  These are
// singleton kernel locks: only one thread can hold them at a time, so any
// two functions that both acquire the same subsystem lock are mutually
// exclusive.
// ---------------------------------------------------------------------------
class SubsystemLockHeuristic : public PairHeuristic {
    // function name → set of subsystem lock names called (e.g. "rtnl_lock")
    std::map<std::string, std::set<std::string>> subsysLocks_;
public:
    explicit SubsystemLockHeuristic(
            std::map<std::string, std::set<std::string>> s)
        : subsysLocks_(std::move(s)) {}

    const char *name() const override { return "SubsystemLock"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// PerCpuHeuristic (H8)
//
// Both functions access the same per-CPU variable via get_cpu_ptr() /
// this_cpu_ptr().  Per-CPU variables have one independent copy per CPU;
// get_cpu_ptr() also disables preemption, so the accessing thread owns
// that CPU's copy exclusively until put_cpu_ptr().  Concurrent access to
// *different* CPUs' copies of the same per-CPU object is not a shared-memory
// race, so such pairs should be filtered.
//
// Object identity: SVF base-object NodeID of the argument to get_cpu_ptr /
// __this_cpu_ptr / raw_cpu_ptr.
// ---------------------------------------------------------------------------
class PerCpuHeuristic : public PairHeuristic {
    // function name → set of per-CPU base-object NodeIDs accessed
    std::map<std::string, std::set<unsigned>> perCpuSets_;
public:
    explicit PerCpuHeuristic(
            std::map<std::string, std::set<unsigned>> s)
        : perCpuSets_(std::move(s)) {}

    const char *name() const override { return "PerCpu"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// SafeAllocationHeuristic (H11 + H15 + H21 + H24 + H25)
//
// The shared object itself is safe to access without external locking:
//   H11: Known-benign global (jiffies, runqueues, cpu_info, …).
//   H15: Seqlock-protected reader/writer — READ_ONCE + retry loop, benign.
//   H21: DMA-sync barrier pair (dma_sync_*_for_cpu / _for_device).
//   H24: regmap accessor (regmap_read/write/update_bits) — map->lock internal.
//   H25: IOMEM-mapped region (*_regs, *_base, *_mmio, *_bar, *_csr) —
//        readl/writel provide necessary ordering barriers.
// ---------------------------------------------------------------------------
class SafeAllocationHeuristic : public PairHeuristic {
    std::set<std::string> regmapFns_;   // fns that use regmap APIs (H24)
    std::set<std::string> dmaSyncFns_;  // fns that call dma_sync_* (H21)
    std::set<std::string> seqlockRdFns_; // fns calling read_seqbegin (H15)
    std::set<std::string> seqlockWrFns_; // fns calling write_seqlock (H15)
public:
    SafeAllocationHeuristic(
        std::set<std::string> regmap,
        std::set<std::string> dmaSync,
        std::set<std::string> seqlockRd,
        std::set<std::string> seqlockWr)
        : regmapFns_(std::move(regmap)),
          dmaSyncFns_(std::move(dmaSync)),
          seqlockRdFns_(std::move(seqlockRd)),
          seqlockWrFns_(std::move(seqlockWr)) {}

    const char *name() const override { return "SafeAllocation"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// RegistrationPublishHeuristic (v10: B1 + B6)
//
// Many kernel drivers run an init/probe function that publishes its private
// state via a "registration" call near the end of probe: request_irq,
// register_console, platform_driver_register, cpufreq_register_driver,
// pm_genpd_init, register_sys_off_handler, cpuhp_setup_state, sysfs_*,
// led_classdev_register, atomic_notifier_chain_register, ...
//
// The kernel guarantees that the registered callback cannot be invoked
// before the registration call returns to its caller.  Therefore every
// store the registering function performs BEFORE the registration call is
// ordered before any invocation of the registered partner callback.
//
// We model this as: if probe registers a callback C, the pair (probe, C)
// is mutually exclusive in the precise sense that probe's stores happen
// strictly before any execution of C.  A causal-ordering anchor inside
// probe paired against an access in C therefore cannot race.
//
// Soundness: only callbacks that are demonstrably argument-passed to a
// known registration API (either directly, or as a Function* field of the
// argument struct's initializer) are entered into the map.  This rules
// out "any callback in this driver" speculation.
// ---------------------------------------------------------------------------
class RegistrationPublishHeuristic : public PairHeuristic {
    // partner-fn-name → set of fn-names that registered partner via a
    // kernel registration API call.
    std::map<std::string, std::set<std::string>> registeredBy_;
public:
    explicit RegistrationPublishHeuristic(
        std::map<std::string, std::set<std::string>> m)
        : registeredBy_(std::move(m)) {}
    const char *name() const override { return "RegistrationPublish"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// PmPhaseHeuristic (v10: B5)
//
// The kernel PM core drives system suspend/resume through a fixed phase
// sequence per cycle:
//   1. _suspend           (per-device .suspend dispatch)
//   2. _suspend_late      (.suspend_late)
//   3. _suspend_noirq     (.suspend_noirq)
//   --- system suspended ---
//   4. _resume_noirq      (.resume_noirq)
//   5. _resume_early      (.resume_early)
//   6. _resume            (.resume)
// (Hibernation has _freeze / _thaw / _poweroff / _restore variants with
//  the same phase relationships.)
//
// Within a single suspend/resume cycle the suspend phases and resume phases
// are temporally disjoint: dpm_list_mtx + the PM state machine serialize
// dispatch per device, and the suspend half completes before the resume
// half begins.  Across cycles the dpm_list_mtx + power_state ordering
// supplies a happens-before edge from the end of cycle N to the start of
// cycle N+1, so cross-cycle reads see prior cycle's writes — not a race.
//
// Pair (suspend-phase fn, resume-phase fn) is therefore mutually exclusive.
// ---------------------------------------------------------------------------
class PmPhaseHeuristic : public PairHeuristic {
public:
    const char *name() const override { return "PmPhase"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// SeqcountReaderWriterHeuristic (v10: B2)
//
// Kernel `seqcount_*` is a lockless read/write synchronization primitive.
// Writers hold an exclusive (raw_)spinlock AND bracket their stores in
// write_seqcount_begin / write_seqcount_end.  Readers do not take any
// lock; they read sequence-begin, do their accesses, then read
// sequence-retry and loop if the sequence changed.  By design the reader
// can observe torn values — the retry hides the tear.  At LKMM level the
// reader's value-load and the writer's value-store both touch the same
// memory with no acquire/release between them; mbcheck therefore reports
// the pair as racy.  In practice the seqcount retry loop makes the read
// safe.
//
// We curate the list of functions on each side for subsystems where the
// seqcount API is fully inlined (timekeeping, etc.) and recognise the
// pair as benign.  Soundness rests on the per-subsystem curation: every
// entry below has been manually verified to hold the write-seqcount /
// read-seqcount pattern.
// ---------------------------------------------------------------------------
class SeqcountReaderWriterHeuristic : public PairHeuristic {
public:
    const char *name() const override { return "SeqcountReadWrite"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// ConservativeAnyLockHeuristic (H2p)
//
// Conservative catch-all: if EITHER function acquires ANY exclusive lock
// (or any transitive callee does), the pair is considered serialized.
// This is the final fallback after all specific heuristics have passed.
//
// Rationale: a function that holds an exclusive lock during its access to
// the shared object cannot race concurrently with another function that also
// holds any lock protecting that object.
//
// Note: this heuristic is intentionally conservative and may suppress some
// valid race reports.  Disable it if false-negative rate is too high.
// ---------------------------------------------------------------------------
class ConservativeAnyLockHeuristic : public PairHeuristic {
    std::set<std::string> anyLockFns_;  // fns that acquire any exclusive lock
public:
    explicit ConservativeAnyLockHeuristic(std::set<std::string> fns)
        : anyLockFns_(std::move(fns)) {}

    const char *name() const override { return "ConservativeAnyLock"; }
    std::string isMutuallyExclusive(const FunctionPair      &pair,
                                    llvm::Module             &M,
                                    llvm::ModuleAnalysisManager &MAM) const override;
};

// ---------------------------------------------------------------------------
// FnHeuristicsFilterResult — pairs that survived all heuristic filters.
// Same shape as FunctionPairsResult; distinct type so LLVM's analysis
// manager can cache it separately.
// ---------------------------------------------------------------------------

// One filtered-out pair with the name and sub-category of the first heuristic
// that matched.
struct FilteredPairRecord {
    FunctionPair pair;
    std::string  heuristicName;
    std::string  subCategory;   // empty string if heuristic has no sub-category
};

struct FnHeuristicsFilterResult {
    // Key: anchor function name.  Only functions with at least one surviving
    // pair are present.
    std::map<std::string, std::vector<FunctionPair>> byAnchorFn;

    // Total fn-pair count before any heuristic filtering.
    int totalPairs = 0;

    // Per-heuristic filter hit counts (key = heuristic name()).
    // A pair is counted under the FIRST heuristic that suppressed it.
    std::map<std::string, int> heuristicHits;

    // Per-heuristic sub-category counts: heuristicSubHits[name][subcat] = count.
    std::map<std::string, std::map<std::string, int>> heuristicSubHits;

    // Every pair that was filtered, in encounter order, with the name of the
    // heuristic that suppressed it.  Used by --summary for verbose log output.
    std::vector<FilteredPairRecord> filteredRecords;

    bool invalidate(llvm::Module &, const llvm::PreservedAnalyses &,
                    llvm::ModuleAnalysisManager::Invalidator &)
    {
        return false;
    }
};

// ---------------------------------------------------------------------------
// FnHeuristicsFilterPass — LLVM module analysis pass.
//
// Obtains FunctionPairsResult, applies every registered heuristic, and
// returns the surviving pairs as FnHeuristicsFilterResult.
//
// The active heuristic set is assembled inside run(); add new heuristics
// there.  The pass itself is stateless and safe to cache.
// ---------------------------------------------------------------------------
class FnHeuristicsFilterPass
    : public llvm::AnalysisInfoMixin<FnHeuristicsFilterPass>
{
    friend struct llvm::AnalysisInfoMixin<FnHeuristicsFilterPass>;
    static llvm::AnalysisKey Key;

public:
    using Result = FnHeuristicsFilterResult;
    Result run(llvm::Module &M, llvm::ModuleAnalysisManager &MAM);
};
